<?php
fwrite($hell, "#cms_rechtepapa {\n");
fwrite($hell, "margin-left: -34px;\n");
fwrite($hell, "}\n");
fwrite($hell, ".cms_rechtebox {\n");
fwrite($hell, "margin-left: 24px;\n");
fwrite($hell, "&:not(.cms_recht_unterstes) {\n");
fwrite($hell, "background-size: 24px;\n");
fwrite($hell, "background-image: url('../res/sonstiges/rechtebaum/leer.png');\n");
fwrite($hell, "background-repeat: repeat-y;\n");
fwrite($hell, "}\n");
fwrite($hell, ".cms_recht {\n");
// Icon
fwrite($hell, "&>.icon {\n");
fwrite($hell, "content: ' ';\n");
fwrite($hell, "display: inline-block;\n");
fwrite($hell, "background-size: cover;\n");
fwrite($hell, "background-image: url('../res/sonstiges/rechtebaum/wert.png');\n");
fwrite($hell, "line-height: 24px;\n");
fwrite($hell, "float: left;\n");
fwrite($hell, "height: 24px;\n");
fwrite($hell, "width:  24px;\n");
fwrite($hell, "}\n");
fwrite($hell, "&.cms_hat_kinder {\n");
fwrite($hell, "&>.icon {\n");
fwrite($hell, "cursor: pointer;\n");
fwrite($hell, "background-image: url('../res/sonstiges/rechtebaum/wert_k.png');\n");
fwrite($hell, "&.cms_recht_eingeklappt {\n");
fwrite($hell, "background-image: url('../res/sonstiges/rechtebaum/wert_k_c.png');\n");
fwrite($hell, "}\n");
fwrite($hell, "}\n");
fwrite($hell, "}\n");
fwrite($hell, "&.cms_recht_unterstes {\n");
fwrite($hell, "&>.icon {\n");
fwrite($hell, "background-image: url('../res/sonstiges/rechtebaum/wert_u.png');\n");
fwrite($hell, "}\n");
fwrite($hell, "}\n");
fwrite($hell, "&.cms_recht_unterstes.cms_hat_kinder {\n");
fwrite($hell, "&>.icon {\n");
fwrite($hell, "background-image: url('../res/sonstiges/rechtebaum/wert_u_k.png');\n");
fwrite($hell, "&.cms_recht_eingeklappt {\n");
fwrite($hell, "background-image: url('../res/sonstiges/rechtebaum/wert_u_k_c.png');\n");
fwrite($hell, "}\n");
fwrite($hell, "}\n");
fwrite($hell, "}\n");
fwrite($hell, ".cms_recht_beschreibung {\n");
fwrite($hell, "height: 24px;\n");
fwrite($hell, "display: inline-block;\n");
fwrite($hell, ".cms_recht_beschreibung_i {\n");
fwrite($hell, "height: 20px;\n");
fwrite($hell, "cursor: pointer;\n");
fwrite($hell, "transition: 250ms ease-in-out;\n");
fwrite($hell, "border-radius: 1px;\n");
fwrite($hell, "padding: 3px;\n");
fwrite($hell, "margin: 2px;\n");
fwrite($hell, "display: inline-block;\n");
fwrite($hell, "border: 1px solid ".$_POST['cms_style_h_haupt_schriftfarbepositiv'].";\n");
fwrite($hell, "&:hover {\n");
fwrite($hell, "border-color: transparent;\n");
fwrite($hell, "color: ".$_POST['cms_style_h_button_schrift'].";\n");
fwrite($hell, "background-color: ".$_POST['cms_style_h_button_hintergrund'].";\n");
fwrite($hell, "}\n");
fwrite($hell, "}\n");
fwrite($hell, "}\n");
fwrite($hell, "&.cms_recht_nutzer {\n");
fwrite($hell, ".cms_recht_beschreibung_i {\n");
fwrite($hell, "border-color: transparent;\n");
fwrite($hell, "color: ".$_POST['cms_style_h_haupt_schriftfarbepositiv'].";\n");
fwrite($hell, "background-color: ".$_POST['cms_style_h_haupt_meldungerfolghinter'].";\n");
fwrite($hell, "&:hover {\n");
fwrite($hell, "background-color: ".$_POST['cms_style_h_haupt_meldungfehlerhinter'].";\n");
fwrite($hell, "}\n");
fwrite($hell, "}\n");
fwrite($hell, "}\n");
fwrite($hell, "&.cms_recht_rolle {\n");
fwrite($hell, ".cms_recht_beschreibung_i {\n");
fwrite($hell, "border-color: transparent;\n");
fwrite($hell, "cursor: default;\n");
fwrite($hell, "background-color: ".$_POST['cms_style_h_haupt_meldunginfohinter']." !important;\n");
fwrite($hell, "color: ".$_POST['cms_style_h_haupt_schriftfarbepositiv']." !important;\n");
fwrite($hell, "}\n");
fwrite($hell, "}\n");
fwrite($hell, "}\n");
fwrite($hell, "}\n");

fwrite($hell, ".cms_demorecht {\n");
fwrite($hell, "height: 24px;\n");
fwrite($hell, "display: inline-block;\n");
fwrite($hell, "padding: 5px;\n");
fwrite($hell, "margin-bottom: 2px;\n");
fwrite($hell, "border-radius: 1px;\n");
fwrite($hell, "cursor: pointer;\n");
fwrite($hell, "transition: 250ms ease-in-out;\n");
fwrite($hell, "border: 1px solid ".$_POST['cms_style_h_haupt_schriftfarbepositiv'].";\n");
fwrite($hell, "&:hover {\n");
fwrite($hell, "border-color: transparent;\n");
fwrite($hell, "color: ".$_POST['cms_style_h_button_schrift'].";\n");
fwrite($hell, "background-color: ".$_POST['cms_style_h_button_hintergrund'].";\n");
fwrite($hell, "}\n");
fwrite($hell, "&.cms_demorecht_nutzer {\n");
fwrite($hell, "border-color: transparent;\n");
fwrite($hell, "color: ".$_POST['cms_style_h_haupt_schriftfarbepositiv'].";\n");
fwrite($hell, "background-color: ".$_POST['cms_style_h_haupt_meldungerfolghinter'].";\n");
fwrite($hell, "&:hover {\n");
fwrite($hell, "background-color: ".$_POST['cms_style_h_haupt_meldungfehlerhinter'].";\n");
fwrite($hell, "}\n");
fwrite($hell, "}\n");
fwrite($hell, "&.cms_demorecht_rolle {\n");
fwrite($hell, "border-color: transparent;\n");
fwrite($hell, "cursor: default;\n");
fwrite($hell, "background-color: ".$_POST['cms_style_h_haupt_meldunginfohinter']." !important;\n");
fwrite($hell, "color: ".$_POST['cms_style_h_haupt_schriftfarbepositiv']." !important;\n");
fwrite($hell, "}\n");
fwrite($hell, "}\n");



// DARKMODE
fwrite($dunkel, ".cms_rechtebox {\n");
fwrite($dunkel, ".cms_recht {\n");
fwrite($dunkel, ".cms_recht_beschreibung {\n");
fwrite($dunkel, ".cms_recht_beschreibung_i {\n");
fwrite($dunkel, "border: 1px solid ".$_POST['cms_style_d_haupt_schriftfarbepositiv'].";\n");
fwrite($dunkel, "&:hover {\n");
fwrite($dunkel, "color: ".$_POST['cms_style_d_button_schrift'].";\n");
fwrite($dunkel, "background-color: ".$_POST['cms_style_d_button_hintergrund'].";\n");
fwrite($dunkel, "}\n");
fwrite($dunkel, "}\n");
fwrite($dunkel, "}\n");
fwrite($dunkel, "&.cms_recht_nutzer {\n");
fwrite($dunkel, ".cms_recht_beschreibung_i {\n");
fwrite($dunkel, "color: ".$_POST['cms_style_d_haupt_schriftfarbepositiv'].";\n");
fwrite($dunkel, "background-color: ".$_POST['cms_style_d_haupt_meldungerfolghinter'].";\n");
fwrite($dunkel, "&:hover {\n");
fwrite($dunkel, "background-color: ".$_POST['cms_style_d_haupt_meldungfehlerhinter'].";\n");
fwrite($dunkel, "}\n");
fwrite($dunkel, "}\n");
fwrite($dunkel, "}\n");
fwrite($dunkel, "&.cms_recht_rolle {\n");
fwrite($dunkel, ".cms_recht_beschreibung_i {\n");
fwrite($dunkel, "background-color: ".$_POST['cms_style_d_haupt_meldunginfohinter']." !important;\n");
fwrite($dunkel, "color: ".$_POST['cms_style_d_haupt_schriftfarbepositiv']." !important;\n");
fwrite($dunkel, "}\n");
fwrite($dunkel, "}\n");
fwrite($dunkel, "}\n");
fwrite($dunkel, "}\n");

fwrite($dunkel, ".cms_demorecht {\n");
fwrite($dunkel, "border: 1px solid ".$_POST['cms_style_d_haupt_schriftfarbepositiv'].";\n");
fwrite($dunkel, "&:hover {\n");
fwrite($dunkel, "color: ".$_POST['cms_style_d_button_schrift'].";\n");
fwrite($dunkel, "background-color: ".$_POST['cms_style_d_button_hintergrund'].";\n");
fwrite($dunkel, "}\n");
fwrite($dunkel, "&.cms_demorecht_nutzer {\n");
fwrite($dunkel, "color: ".$_POST['cms_style_d_haupt_schriftfarbepositiv'].";\n");
fwrite($dunkel, "background-color: ".$_POST['cms_style_d_haupt_meldungerfolghinter'].";\n");
fwrite($dunkel, "&:hover {\n");
fwrite($dunkel, "background-color: ".$_POST['cms_style_d_haupt_meldungfehlerhinter'].";\n");
fwrite($dunkel, "}\n");
fwrite($dunkel, "}\n");
fwrite($dunkel, "&.cms_demorecht_rolle {\n");
fwrite($dunkel, "background-color: ".$_POST['cms_style_d_haupt_meldunginfohinter']." !important;\n");
fwrite($dunkel, "color: ".$_POST['cms_style_d_haupt_schriftfarbepositiv']." !important;\n");
fwrite($dunkel, "}\n");
fwrite($dunkel, "}\n");
?>
