<?php

fwrite($hell, "#cms_rechtepapa {");
fwrite($hell, "margin-left: -34px;");
fwrite($hell, "}");
fwrite($hell, ".cms_rechtebox {");
fwrite($hell, "margin-left: 24px;");
fwrite($hell, "&:not(.cms_recht_unterstes) {");
fwrite($hell, "background-size: 24px;");
fwrite($hell, "background-image: url('../res/sonstiges/rechtebaum/leer.png');");
fwrite($hell, "background-repeat: repeat-y;");
fwrite($hell, "}");
fwrite($hell, ".cms_recht {");
fwrite($hell, "// Icon");
fwrite($hell, "&>.icon {");
fwrite($hell, "content: ' ';");
fwrite($hell, "display: inline-block;");
fwrite($hell, "background-size: cover;");
fwrite($hell, "background-image: url('../res/sonstiges/rechtebaum/wert.png');");
fwrite($hell, "line-height: 24px;");
fwrite($hell, "float: left;");
fwrite($hell, "height: 24px;");
fwrite($hell, "width:  24px;");
fwrite($hell, "}");
fwrite($hell, "&.cms_hat_kinder {");
fwrite($hell, "&>.icon {");
fwrite($hell, "cursor: pointer;");
fwrite($hell, "background-image: url('../res/sonstiges/rechtebaum/wert_k.png');");
fwrite($hell, "&.cms_recht_eingeklappt {");
fwrite($hell, "background-image: url('../res/sonstiges/rechtebaum/wert_k_c.png');");
fwrite($hell, "}");
fwrite($hell, "}");
fwrite($hell, "}");
fwrite($hell, "&.cms_recht_unterstes {");
fwrite($hell, "&>.icon {");
fwrite($hell, "background-image: url('../res/sonstiges/rechtebaum/wert_u.png');");
fwrite($hell, "}");
fwrite($hell, "}");
fwrite($hell, "&.cms_recht_unterstes.cms_hat_kinder {");
fwrite($hell, "&>.icon {");
fwrite($hell, "background-image: url('../res/sonstiges/rechtebaum/wert_u_k.png');");
fwrite($hell, "&.cms_recht_eingeklappt {");
fwrite($hell, "background-image: url('../res/sonstiges/rechtebaum/wert_u_k_c.png');");
fwrite($hell, "}");
fwrite($hell, "}");
fwrite($hell, "}");
fwrite($hell, ".cms_recht_beschreibung {");
fwrite($hell, "height: 24px;");
fwrite($hell, "display: inline-block;");
fwrite($hell, ".cms_recht_beschreibung_i {");
fwrite($hell, "height: 20px;");
fwrite($hell, "cursor: pointer;");
fwrite($hell, "transition: 250ms ease-in-out;");
fwrite($hell, "border-radius: 1px;");
fwrite($hell, "padding: 3px;");
fwrite($hell, "margin: 2px;");
fwrite($hell, "display: inline-block;");
fwrite($hell, "border: 1px solid ".$_POST['cms_style_d_haupt_hintergrund'].";");
fwrite($hell, "&:hover {");
fwrite($hell, "border-color: transparent;");
fwrite($hell, "color: ".$_POST['cms_style_h_button_schrift'].";");
fwrite($hell, "background-color: ".$_POST['cms_style_h_button_hintergrund'].";");
fwrite($hell, "}");
fwrite($hell, "}");
fwrite($hell, "}");
fwrite($hell, "&.cms_recht_nutzer {");
fwrite($hell, ".cms_recht_beschreibung_i {");
fwrite($hell, "border-color: transparent;");
fwrite($hell, "color: ".$_POST['cms_style_h_haupt_schriftfarbepositiv'].";");
fwrite($hell, "background-color: ".$_POST['cms_style_h_haupt_meldungerfolghinter'].";");
fwrite($hell, "&:hover {");
fwrite($hell, "background-color: ".$_POST['cms_style_h_haupt_meldungfehlerhinter'].";");
fwrite($hell, "}");
fwrite($hell, "}");
fwrite($hell, "}");
fwrite($hell, "&.cms_recht_rolle {");
fwrite($hell, ".cms_recht_beschreibung_i {");
fwrite($hell, "border-color: transparent;");
fwrite($hell, "cursor: default;");
fwrite($hell, "background-color: ".$_POST['cms_style_h_haupt_meldunginfohinter']." !important;");
fwrite($hell, "color: ".$_POST['cms_style_h_haupt_schriftfarbepositiv']." !important;");
fwrite($hell, "}");
fwrite($hell, "}");
fwrite($hell, "}");
fwrite($hell, "}");

fwrite($hell, ".cms_demorecht {");
fwrite($hell, "height: 24px;");
fwrite($hell, "display: inline-block;");
fwrite($hell, "padding: 5px;");
fwrite($hell, "margin-bottom: 2px;");
fwrite($hell, "border-radius: 1px;");
fwrite($hell, "cursor: pointer;");
fwrite($hell, "transition: 250ms ease-in-out;");
fwrite($hell, "border: 1px solid ".$_POST['cms_style_d_haupt_hintergrund'].";");
fwrite($hell, "&:hover {");
fwrite($hell, "border-color: transparent;");
fwrite($hell, "color: ".$_POST['cms_style_h_button_schrift'].";");
fwrite($hell, "background-color: ".$_POST['cms_style_h_button_hintergrund'].";");
fwrite($hell, "}");
fwrite($hell, "&.cms_demorecht_nutzer {");
fwrite($hell, "border-color: transparent;");
fwrite($hell, "color: ".$_POST['cms_style_h_haupt_schriftfarbepositiv'].";");
fwrite($hell, "background-color: ".$_POST['cms_style_h_haupt_meldungerfolghinter'].";");
fwrite($hell, "&:hover {");
fwrite($hell, "background-color: ".$_POST['cms_style_h_haupt_meldungfehlerhinter'].";");
fwrite($hell, "}");
fwrite($hell, "}");
fwrite($hell, "&.cms_demorecht_rolle {");
fwrite($hell, "border-color: transparent;");
fwrite($hell, "cursor: default;");
fwrite($hell, "background-color: ".$_POST['cms_style_h_haupt_meldunginfohinter']." !important;");
fwrite($hell, "color: ".$_POST['cms_style_h_haupt_schriftfarbepositiv']." !important;");
fwrite($hell, "}");
fwrite($hell, "}");



// DARKMODE
fwrite($hell, ".cms_rechtebox {");
fwrite($dunkel, ".cms_recht {");
fwrite($dunkel, ".cms_recht_beschreibung {");
fwrite($dunkel, ".cms_recht_beschreibung_i {");
fwrite($dunkel, "border: 1px solid ".$_POST['cms_style_h_haupt_hintergrund'].";");
fwrite($dunkel, "&:hover {");
fwrite($dunkel, "color: ".$_POST['cms_style_d_button_schrift'].";");
fwrite($dunkel, "background-color: ".$_POST['cms_style_d_button_hintergrund'].";");
fwrite($dunkel, "}");
fwrite($dunkel, "}");
fwrite($dunkel, "}");
fwrite($dunkel, "&.cms_recht_nutzer {");
fwrite($dunkel, ".cms_recht_beschreibung_i {");
fwrite($dunkel, "color: ".$_POST['cms_style_d_haupt_schriftfarbepositiv'].";");
fwrite($dunkel, "background-color: ".$_POST['cms_style_h_haupt_meldungerfolgakzent'].";");
fwrite($dunkel, "&:hover {");
fwrite($dunkel, "background-color: ".$_POST['cms_style_h_haupt_meldungfehlerakzent'].";");
fwrite($dunkel, "}");
fwrite($dunkel, "}");
fwrite($dunkel, "}");
fwrite($dunkel, "&.cms_recht_rolle {");
fwrite($dunkel, ".cms_recht_beschreibung_i {");
fwrite($dunkel, "background-color: ".$_POST['cms_style_h_haupt_meldunginfoakzent']." !important;");
fwrite($dunkel, "color: ".$_POST['cms_style_d_haupt_schriftfarbepositiv']." !important;");
fwrite($dunkel, "}");
fwrite($dunkel, "}");
fwrite($dunkel, "}");
fwrite($dunkel, "}");

fwrite($dunkel, ".cms_demorecht {");
fwrite($dunkel, "border: 1px solid ".$_POST['cms_style_h_haupt_hintergrund'].";");
fwrite($dunkel, "&:hover {");
fwrite($dunkel, "color: ".$_POST['cms_style_d_button_schrift'].";");
fwrite($dunkel, "background-color: ".$_POST['cms_style_d_button_hintergrund'].";");
fwrite($dunkel, "}");
fwrite($dunkel, "&.cms_demorecht_nutzer {");
fwrite($dunkel, "color: ".$_POST['cms_style_d_haupt_schriftfarbepositiv'].";");
fwrite($dunkel, "background-color: ".$_POST['cms_style_h_haupt_meldungerfolgakzent'].";");
fwrite($dunkel, "&:hover {");
fwrite($dunkel, "background-color: ".$_POST['cms_style_h_haupt_meldungfehlerakzent'].";");
fwrite($dunkel, "}");
fwrite($dunkel, "}");
fwrite($dunkel, "&.cms_demorecht_rolle {");
fwrite($dunkel, "background-color: ".$_POST['cms_style_h_haupt_meldunginfoakzent']." !important;");
fwrite($dunkel, "color: ".$_POST['cms_style_d_haupt_schriftfarbepositiv']." !important;");
fwrite($dunkel, "}");
fwrite($dunkel, "}");
fwrite($dunkel, "}");
?>
