-- Format:
--
-- <Commit Hash, seit dem die SQL notwendig ist>:
-- <SQL Änderungen>

-- <155d38693dea61b63421d896c92c8ace97f2798c>
ALTER TABLE `rythmisierung` CHANGE `jahr` `beginn` BIGINT(255) UNSIGNED NOT NULL;

-- <>
CREATE TABLE `unterricht` ( `id` BIGINT(255) UNSIGNED NOT NULL , `pbeginn` BIGINT(255) UNSIGNED NOT NULL , `pende` BIGINT(255) UNSIGNED NOT NULL , `pkurs` BIGINT(255) UNSIGNED NOT NULL , `plehrer` BIGINT(255) UNSIGNED NOT NULL , `praum` BIGINT(255) UNSIGNED NOT NULL , `tbeginn` BIGINT(255) UNSIGNED NOT NULL , `tende` BIGINT(255) UNSIGNED NOT NULL , `tkurs` BIGINT(255) UNSIGNED NOT NULL , `tlehrer` BIGINT(255) UNSIGNED NOT NULL , `traum` BIGINT(255) UNSIGNED NOT NULL , `vplananzeigen` TINYINT(1) UNSIGNED NOT NULL , `vplanart` VARBINARY(50) NOT NULL , `vplanbemerkung` VARBINARY(5000) NOT NULL , `idvon` BIGINT(255) UNSIGNED NULL , `idzeit` BIGINT(255) UNSIGNED NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB CHARSET=utf8 COLLATE utf8_unicode_ci;
ALTER TABLE `unterricht` ADD CONSTRAINT `unterrichtkurs` FOREIGN KEY (`tkurs`) REFERENCES `kurse`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `unterricht` ADD CONSTRAINT `unterrichtlehrer` FOREIGN KEY (`tlehrer`) REFERENCES `lehrer`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE `unterricht` ADD CONSTRAINT `unterrichtraum` FOREIGN KEY (`traum`) REFERENCES `raeume`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;
