<?php
function cms_configaendern() {
	global $CMS_SCHLUESSEL, $CMS_SCHULE, $CMS_SCHULE_GENITIV, $CMS_ORT, $CMS_STRASSE, $CMS_PLZORT, $CMS_LOGO;
	global $CMS_WEBMASTER, $CMS_DOMAIN, $CMS_MAILABSENDER, $CMS_MAILHOST, $CMS_MAILSMTPAUTH, $CMS_MAILUSERNAME, $CMS_MAILPASSWORT;
	global $CMS_DBS_HOST, $CMS_DBS_USER, $CMS_DBS_PASS, $CMS_DBS_DB,$CMS_DBP_DB, $CMS_BASE;
	global $CMS_LN_ZB_VPN, $CMS_LN_DA, $CMS_DBV_HOST, $CMS_DBV_USER, $CMS_DBV_PASS, $CMS_DBV_DB;
	global $CMS_DBN_HOST, $CMS_DBN_USER, $CMS_DBN_PASS, $CMS_DBN_DB, $CMS_MAX_DATEI, $CMS_MAILZ, $CMS_MAILHV, $CMS_MAILHH;
	global $CMS_MAILWV, $CMS_MAILWH, $CMS_MAILSIGNATUR;
	$text  = '<?php'."\r\n";
	$text .= '$CMS_SCHLUESSEL = "'.cms_dateischreiben_vorbereiten($CMS_SCHLUESSEL).'";'."\r\n";
	$text .= "\r\n";
	$text .= '$CMS_SCHULE = "'.cms_dateischreiben_vorbereiten($CMS_SCHULE).'";'."\r\n";
	$text .= '$CMS_SCHULE_GENITIV = "'.cms_dateischreiben_vorbereiten($CMS_SCHULE_GENITIV).'";'."\r\n";
	$text .= '$CMS_ORT = "'.cms_dateischreiben_vorbereiten($CMS_ORT).'";'."\r\n";
	$text .= '$CMS_STRASSE = "'.cms_dateischreiben_vorbereiten($CMS_STRASSE).'";'."\r\n";
	$text .= '$CMS_PLZORT = "'.cms_dateischreiben_vorbereiten($CMS_PLZORT).'";'."\r\n";
	$text .= '$CMS_LOGO = "'.cms_dateischreiben_vorbereiten($CMS_LOGO).'";'."\r\n";
	$text .= "\r\n";
	$text .= '$CMS_WEBMASTER = "'.cms_dateischreiben_vorbereiten($CMS_WEBMASTER).'";'."\r\n";
	$text .= '$CMS_DOMAIN = "'.cms_dateischreiben_vorbereiten($CMS_DOMAIN).'";'."\r\n";
	$text .= "\r\n";
	$text .= '$CMS_MAILABSENDER = "'.cms_dateischreiben_vorbereiten($CMS_MAILABSENDER).'";'."\r\n";
	$text .= '$CMS_MAILHOST = "'.cms_dateischreiben_vorbereiten($CMS_MAILHOST).'";'."\r\n";
	if ($CMS_MAILSMTPAUTH) {$text .= '$CMS_MAILSMTPAUTH = true;'."\r\n";} else {$text .= '$CMS_MAILSMTPAUTH = false;'."\r\n";}
	$text .= '$CMS_MAILUSERNAME = "'.cms_dateischreiben_vorbereiten($CMS_MAILUSERNAME).'";'."\r\n";
	$text .= '$CMS_MAILPASSWORT = "'.cms_dateischreiben_vorbereiten($CMS_MAILPASSWORT).'";'."\r\n";
	$text .= "\r\n";
	$text .= '$CMS_DBS_HOST = "'.cms_dateischreiben_vorbereiten($CMS_DBS_HOST).'";'."\r\n";
	$text .= '$CMS_DBS_USER = "'.cms_dateischreiben_vorbereiten($CMS_DBS_USER).'";'."\r\n";
	$text .= '$CMS_DBS_PASS = "'.cms_dateischreiben_vorbereiten($CMS_DBS_PASS).'";'."\r\n";
	$text .= '$CMS_DBS_DB = "'.cms_dateischreiben_vorbereiten($CMS_DBS_DB).'";'."\r\n";
	$text .= '$CMS_DBP_DB = "'.cms_dateischreiben_vorbereiten($CMS_DBP_DB).'";'."\r\n";
	$text .= "\r\n";
	$text .= '$CMS_BASE = "'.cms_dateischreiben_vorbereiten($CMS_BASE).'";'."\r\n";
	$text .= "\r\n";
	$text .= '$CMS_LN_ZB_VPN = '.cms_dateischreiben_vorbereiten($CMS_LN_ZB_VPN).';'."\r\n";
	$text .= '$CMS_LN_DA = "'.cms_dateischreiben_vorbereiten($CMS_LN_DA).'";'."\r\n";
	$text .= "\r\n";
	$text .= '$CMS_DBV_HOST = "'.cms_dateischreiben_vorbereiten($CMS_DBV_HOST).'";'."\r\n";
	$text .= '$CMS_DBV_USER = "'.cms_dateischreiben_vorbereiten($CMS_DBV_USER).'";'."\r\n";
	$text .= '$CMS_DBV_PASS = "'.cms_dateischreiben_vorbereiten($CMS_DBV_PASS).'";'."\r\n";
	$text .= '$CMS_DBV_DB = "'.cms_dateischreiben_vorbereiten($CMS_DBV_DB).'";'."\r\n";
	$text .= "\r\n";
	$text .= '$CMS_DBN_HOST = "'.cms_dateischreiben_vorbereiten($CMS_DBN_HOST).'";'."\r\n";
	$text .= '$CMS_DBN_USER = "'.cms_dateischreiben_vorbereiten($CMS_DBN_USER).'";'."\r\n";
	$text .= '$CMS_DBN_PASS = "'.cms_dateischreiben_vorbereiten($CMS_DBN_PASS).'";'."\r\n";
	$text .= '$CMS_DBN_DB = "'.cms_dateischreiben_vorbereiten($CMS_DBN_DB).'";'."\r\n";
	$text .= "\r\n";
	$text .= '$CMS_MAX_DATEI = '.cms_dateischreiben_vorbereiten($CMS_MAX_DATEI).';'."\r\n";
	$text .= "\r\n";
	$text .= '// GENERIEREN VON MAILS [0] Plain - [1] HTML'."\r\n";
	$text .= '$CMS_MAILZ[0] = "'.cms_dateischreiben_vorbereiten($CMS_MAILZ[0]).'";'."\r\n";
	$text .= '$CMS_MAILZ[1] = "'.cms_dateischreiben_vorbereiten($CMS_MAILZ[1]).'";'."\r\n";
	$text .= '$CMS_MAILHV[0] = "'.cms_dateischreiben_vorbereiten($CMS_MAILHV[0]).'";'."\r\n";
	$text .= '$CMS_MAILHV[1] = "'.cms_dateischreiben_vorbereiten($CMS_MAILHV[1]).'";'."\r\n";
	$text .= '$CMS_MAILHH[0] = "'.cms_dateischreiben_vorbereiten($CMS_MAILHH[0]).'";'."\r\n";
	$text .= '$CMS_MAILHH[1] = "'.cms_dateischreiben_vorbereiten($CMS_MAILHH[1]).'";'."\r\n";
	$text .= '$CMS_MAILWV[0] = "'.cms_dateischreiben_vorbereiten($CMS_MAILWV[0]).'";'."\r\n";
	$text .= '$CMS_MAILWV[1] = "'.cms_dateischreiben_vorbereiten($CMS_MAILWV[1]).'";'."\r\n";
	$text .= '$CMS_MAILWH[0] = "'.cms_dateischreiben_vorbereiten($CMS_MAILWH[0]).'";'."\r\n";
	$text .= '$CMS_MAILWH[1] = "'.cms_dateischreiben_vorbereiten($CMS_MAILWH[1]).'";'."\r\n";
	$text .= "\r\n";
	$text .= '$CMS_MAILSIGNATUR[0] = "Es grüßt das IT-Team des '.cms_dateischreiben_vorbereiten($CMS_SCHULE_GENITIV).' '.cms_dateischreiben_vorbereiten($CMS_ORT).'\\r\\n\\r\\nHinweis: Diese eMail wurde automatisch erstellt. Auf Antworten wird nicht reagiert.\\r\\n\\r\\n\\r\\n-------------------------------------------\\r\\n'.cms_dateischreiben_vorbereiten($CMS_SCHULE).'\\r\\n'.cms_dateischreiben_vorbereiten($CMS_STRASSE).'\\r\\n'.cms_dateischreiben_vorbereiten($CMS_PLZORT).'\\r\\n'.cms_dateischreiben_vorbereiten($CMS_DOMAIN).'";'."\r\n";
	$text .= '$CMS_MAILSIGNATUR[1] = str_replace("\\r\\n", "<br>", $CMS_MAILSIGNATUR[0]);'."\r\n";
	$text .= '?>';
	return $text;
}
?>
