<?php
include_once("../../schulhof/funktionen/check.php");

session_start();

// Variablen einlesen, falls übergeben
if (isset($_SESSION['VORANMELDUNG_VERBINDLICHKEIT'])) {$verbindlichkeit = $_SESSION['VORANMELDUNG_VERBINDLICHKEIT'];} else {echo "FEHLER"; exit;}
if (isset($_SESSION['VORANMELDUNG_GLEICHBEHANDLUNG'])) {$gleichbehandlung = $_SESSION['VORANMELDUNG_GLEICHBEHANDLUNG'];} else {echo "FEHLER"; exit;}
if (isset($_SESSION['VORANMELDUNG_DATENSCHUTZ'])) {$datenschutz = $_SESSION['VORANMELDUNG_DATENSCHUTZ'];} else {echo "FEHLER"; exit;}
if (isset($_SESSION['VORANMELDUNG_COOKIES'])) {$cookies = $_SESSION['VORANMELDUNG_COOKIES'];} else {echo "FEHLER"; exit;}

$fehler = false;
// Pflichteingaben prüfen
if (($verbindlichkeit != 1) || ($gleichbehandlung != 1) || ($datenschutz != 1) || ($cookies != 1)) {
	$fehler = true;
}

if (!$fehler) {
	// Information
	unset($_SESSION['VORANMELDUNG_VERBINDLICHKEIT']);
	unset($_SESSION['VORANMELDUNG_GLEICHBEHANDLUNG']);
	unset($_SESSION['VORANMELDUNG_DATENSCHUTZ']);
	unset($_SESSION['VORANMELDUNG_COOKIES']);
	unset($_SESSION['VORANMELDUNG_FORTSCHITT']);

	// Schüler
	unset($_SESSION['VORANMELDUNG_S_NACHNAME']);
	unset($_SESSION['VORANMELDUNG_S_VORNAME']);
	unset($_SESSION['VORANMELDUNG_S_RUFNAME']);
	unset($_SESSION['VORANMELDUNG_S_GEBURTSDATUM']);
	unset($_SESSION['VORANMELDUNG_S_GEBURTSORT']);
	unset($_SESSION['VORANMELDUNG_S_GEBURTSLAND']);
	unset($_SESSION['VORANMELDUNG_S_MUTTERSPRACHE']);
	unset($_SESSION['VORANMELDUNG_S_VERKEHRSSPRACHE']);
	unset($_SESSION['VORANMELDUNG_S_GESCHLECHT']);
	unset($_SESSION['VORANMELDUNG_S_RELIGION']);
	unset($_SESSION['VORANMELDUNG_S_RELIGIONSUNTERRICHT']);
	unset($_SESSION['VORANMELDUNG_S_LAND1']);
	unset($_SESSION['VORANMELDUNG_S_LAND2']);
	unset($_SESSION['VORANMELDUNG_S_STRASSE']);
	unset($_SESSION['VORANMELDUNG_S_HAUSNUMMER']);
	unset($_SESSION['VORANMELDUNG_S_PLZ']);
	unset($_SESSION['VORANMELDUNG_S_ORT']);
	unset($_SESSION['VORANMELDUNG_S_TEILORT']);
	unset($_SESSION['VORANMELDUNG_S_TELEFON1']);
	unset($_SESSION['VORANMELDUNG_S_TELEFON2']);
	unset($_SESSION['VORANMELDUNG_S_HANDY1']);
	unset($_SESSION['VORANMELDUNG_S_HANDY2']);
	unset($_SESSION['VORANMELDUNG_S_MAIL']);
	unset($_SESSION['VORANMELDUNG_S_EINSCHULUNG']);
	unset($_SESSION['VORANMELDUNG_S_VORIGESCHULE']);
	unset($_SESSION['VORANMELDUNG_S_KLASSE']);
	unset($_SESSION['VORANMELDUNG_S_PROFIL']);

	// Ansprechpartner
	unset($_SESSION['VORANMELDUNG_A1_NACHNAME']);
	unset($_SESSION['VORANMELDUNG_A1_VORNAME']);
	unset($_SESSION['VORANMELDUNG_A1_GESCHLECHT']);
	unset($_SESSION['VORANMELDUNG_A1_SORGERECHT']);
	unset($_SESSION['VORANMELDUNG_A1_BRIEFE']);
	unset($_SESSION['VORANMELDUNG_A1_STRASSE']);
	unset($_SESSION['VORANMELDUNG_A1_HAUSNUMMER']);
	unset($_SESSION['VORANMELDUNG_A1_PLZ']);
	unset($_SESSION['VORANMELDUNG_A1_ORT']);
	unset($_SESSION['VORANMELDUNG_A1_TEILORT']);
	unset($_SESSION['VORANMELDUNG_A1_TELEFON1']);
	unset($_SESSION['VORANMELDUNG_A1_TELEFON2']);
	unset($_SESSION['VORANMELDUNG_A1_HANDY1']);
	unset($_SESSION['VORANMELDUNG_A1_MAIL']);
	unset($_SESSION['VORANMELDUNG_A2']);
	unset($_SESSION['VORANMELDUNG_A2_NACHNAME']);
	unset($_SESSION['VORANMELDUNG_A2_VORNAME']);
	unset($_SESSION['VORANMELDUNG_A2_GESCHLECHT']);
	unset($_SESSION['VORANMELDUNG_A2_SORGERECHT']);
	unset($_SESSION['VORANMELDUNG_A2_BRIEFE']);
	unset($_SESSION['VORANMELDUNG_A2_STRASSE']);
	unset($_SESSION['VORANMELDUNG_A2_HAUSNUMMER']);
	unset($_SESSION['VORANMELDUNG_A2_PLZ']);
	unset($_SESSION['VORANMELDUNG_A2_ORT']);
	unset($_SESSION['VORANMELDUNG_A2_TEILORT']);
	unset($_SESSION['VORANMELDUNG_A2_TELEFON1']);
	unset($_SESSION['VORANMELDUNG_A2_TELEFON2']);
	unset($_SESSION['VORANMELDUNG_A2_HANDY1']);
	unset($_SESSION['VORANMELDUNG_A2_MAIL']);

	echo "ERFOLG";
}
else {
	echo "FEHLER";
}
?>
